export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_FAILER = 'AUTH_FAILER';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILER = 'LOGIN_FAILER';

export const USER_PROFILE = 'USER_PROFILE';
export const PROFILE_FAILER = 'PROFILE_FAILER';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const LOGOUT = 'LOGOUT';
