export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_FAILER = 'AUTH_FAILER';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILER = 'LOGIN_FAILER';

export const USER_PROFILE = 'USER_PROFILE';
export const USER_PROFILES = 'USER_PROFILES';
export const PROFILE_FAILER = 'PROFILE_FAILER';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const GITHUB_REPOS = 'GITHUB_REPOS';

export const GET_POSTS = 'GET_POSTS';
export const POST_FAILER = 'POST_FAILER';
export const POST_UPDATE_LIKES = 'POST_UPDATE_LIKES';
export const DELETE_POST = "DELETE_POST"

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

export const LOGOUT = 'LOGOUT';
